PY-54 join room handler
WinterCitizen/roulette pull request #13
Opened 2023-07-27 08:59 UTC by UlanDT

2023-07-29 13:10 UTC, aalysher approved these changes

2023-07-30 08:54 UTC, WinterCitizen requested changes

2023-07-30 08:54 UTC, WinterCitizen commented on src/back/interfaces/room.py
> +        raise NotImplementedError
Let's just make room simple dataclass. I feel like we are taking all these interfaces too far. It'll be much easier too work with.

2023-07-30 08:54 UTC, WinterCitizen commented on src/back/interfaces/user.py
> +        raise NotImplementedError
Same thing. Just a dataclass

2023-08-07 14:39 UTC, WinterCitizen approved these changes

2023-08-07 14:50 UTC, aalysher approved these changes

2023-08-07 14:58 UTC, merged